### ISSUE TITLE
MORE/EDIT doesnt work on some server listing

### ISSUE THREAD

**Issue by asimzeeshan** [cp6/my-idlers#2]
Sometimes, on some entries, "MORE" button doesnt show anything
"EDIT" button doesnt show anything as well.

Checked database and everything seems to be fine there

**Comment by cp6** [comment]
This is something I did occasionally notice but couldn't pinpoint nor could I replicate it enough. Perhaps a check is needed when calling the modal to see if it loaded correctly.

**Comment by asimzeeshan** [comment]
On one occasion, the provider was new "Prometeus" and on another I added a new location "South Carolina, USA"

may be its related, not sure

**Comment by Mio-sha512** [comment]
For me it seems to have something to do with my yabs test

**Comment by cp6** [comment]
For @asimzeeshan situation it was due to all the YAB's having "busy" as the network bench result which means there was no values to fetch from the database causing the qury to fail. 

It was fixed [here](https://github.com/cp6/my-idlers/commit/ee8651b82eaafb364dbb9c5d33e5ea12bcf94c1d)

**Comment by Mio-sha512** [comment]
Im still having the issue 
`# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #
#              Yet-Another-Bench-Script              #
#                     v2020-12-29                    #
# https://github.com/masonr/yet-another-bench-script #
# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #

Fri Jan 29 15:00:36 CET 2021

Basic System Information:
---------------------------------
Processor  : Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz
CPU cores  : 1 @ 1937.988 MHz
AES-NI     : ✔ Enabled
VM-x/AMD-V : ✔ Enabled
RAM        : 1.0 GiB
Swap       : 0.0 KiB
Disk       : 19.6 GiB

fio Disk Speed Tests (Mixed R/W 50/50):
---------------------------------
Block Size | 4k            (IOPS) | 64k           (IOPS)
  ------   | ---            ----  | ----           ---- 
Read       | 400.00 KB/s    (100) | 4.15 MB/s       (64)
Write      | 423.00 KB/s    (105) | 4.45 MB/s       (69)
Total      | 823.00 KB/s    (205) | 8.61 MB/s      (133)
           |                      |                     
Block Size | 512k          (IOPS) | 1m            (IOPS)
  ------   | ---            ----  | ----           ---- 
Read       | 18.48 MB/s      (36) | 16.62 MB/s      (16)
Write      | 20.17 MB/s      (39) | 17.88 MB/s      (17)
Total      | 38.65 MB/s      (75) | 34.50 MB/s      (33)

iperf3 Network Speed Tests (IPv4):
---------------------------------
Provider        | Location (Link)           | Send Speed      | Recv Speed     
                |                           |                 |                
Clouvider       | London, UK (10G)          | 932 Mbits/sec   | 929 Mbits/sec  
Online.net      | Paris, FR (10G)           | 926 Mbits/sec   | 935 Mbits/sec  
WorldStream     | The Netherlands (10G)     | 929 Mbits/sec   | 938 Mbits/sec  
Biznet          | Jakarta, Indonesia (1G)   | 536 Mbits/sec   | 512 Mbits/sec  
Clouvider       | NYC, NY, US (10G)         | 371 Mbits/sec   | 383 Mbits/sec  
Velocity Online | Tallahassee, FL, US (10G) | 677 Mbits/sec   | 476 Mbits/sec  
Clouvider       | Los Angeles, CA, US (10G) | 474 Mbits/sec   | 390 Mbits/sec  
Iveloz Telecom  | Sao Paulo, BR (2G)        | busy            | busy           

iperf3 Network Speed Tests (IPv6):
---------------------------------
Provider        | Location (Link)           | Send Speed      | Recv Speed     
                |                           |                 |                
Clouvider       | London, UK (10G)          | 912 Mbits/sec   | 920 Mbits/sec  
Online.net      | Paris, FR (10G)           | 920 Mbits/sec   | 922 Mbits/sec  
WorldStream     | The Netherlands (10G)     | 914 Mbits/sec   | 924 Mbits/sec  
Clouvider       | NYC, NY, US (10G)         | 735 Mbits/sec   | 225 Mbits/sec  
Clouvider       | Los Angeles, CA, US (10G) | 389 Mbits/sec   | 247 Mbits/sec  

Geekbench 5 Benchmark Test:
---------------------------------
Test            | Value                         
                |                               
Single Core     | 503                           
Multi Core      | 498                           
Full Test       | https://browser.geekbench.com/v5/cpu/6184341
`
I'm not sure what's causing it

**Comment by cp6** [comment]
@Mio-sha512 i have a feeling it’s the KB/s disk test result.

**Comment by Mio-sha512** [comment]
I tested it with changed values and it still broke (i also changed the swap to 1 mb and i changed the kb/s to mb/s)

**Comment by cp6** [comment]
@Mio-sha512 It worked fine for me

![card](https://i.imgur.com/V6N61hB.png "card")

**Comment by Mio-sha512** [comment]
I think i'm missing something on my side like a php module or something because replicating the exact server in the image it still breaks.

**Comment by cp6** [comment]
@Mio-sha512  PHP 7.4.6 and the YABs you posted above works. Are you making sure there arent any blank lines in the text box when you paste it?

**Comment by Mio-sha512** [comment]
```
PHP 7.4.14 (cli) (built: Jan 13 2021 08:04:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.14, Copyright (c), by Zend Technologies
```
There was no empty lines

**Comment by Mio-sha512** [comment]
https://imgur.com/8T73vxu This is what happens when it try's to fetch the front page

**Comment by cp6** [comment]
HTTP 500 means therre is a PHP error that breaks before being reported. I am assuming that the YABs got inserted but obviously incorrectly which is causing a DB Select query to fail. 

Are you able to get that ID (if you know it) DB row for me (removing sensitive data)?

**Comment by Mio-sha512** [comment]
Not this was what you meant but here's the row in json
```
[{"id":"oFIQETR3","hostname":"test.domain.com","location":"63","provider":"25","ipv4":"1.1.1.1","ipv6":null,"ns1":"ns1","ns2":"ns2","virt":"KVM","cpu":"1","cpu_type":null,"cpu_freq":null,"ram":null,"ram_mb":null,"ram_type":"MB","swap":null,"swap_mb":null,"swap_type":"MB","disk":null,"disk_gb":null,"disk_type":"GB","bandwidth":"4","bandwidth_type":"TB","gb5_single":null,"gb5_multi":null,"gb5_id":null,"aes_ni":"0","amd_v":"0","is_dedicated":"0","is_cpu_dedicated":"0","was_special":"0","os":"17","ssh_port":"22","still_have":"1","owned_since":"2017-01-01","tags":null,"notes":null,"has_yabs":"1","has_st":"0"}]
```

**Comment by cp6** [comment]
Thanks. Having majority of the data being null would be causing an issue or several. Im just not sure why the YABs insert isnt functioning correctly for you. Have other YABs worked?

**Comment by Mio-sha512** [comment]
I've just tested with yabs example and that's not working either 
```
# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #
#              Yet-Another-Bench-Script              #
#                     v2020-09-21                    #
# https://github.com/masonr/yet-another-bench-script #
# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #

Mon 21 Sep 2020 12:31:13 AM EDT

Basic System Information:
---------------------------------
Processor  : Intel(R) Xeon(R) E-2276G CPU @ 3.80GHz
CPU cores  : 12 @ 800.087 MHz
AES-NI     : ✔ Enabled
VM-x/AMD-V : ✔ Enabled
RAM        : 15Gi
Swap       : 14Gi
Disk       : 865G

fio Disk Speed Tests (Mixed R/W 50/50):
---------------------------------
Block Size | 4k            (IOPS) | 64k           (IOPS)
  ------   | ---            ----  | ----           ----
Read       | 445.04 MB/s (111.2k) | 475.05 MB/s   (7.4k)
Write      | 446.22 MB/s (111.5k) | 477.55 MB/s   (7.4k)
Total      | 891.26 MB/s (222.8k) | 952.60 MB/s  (14.8k)
           |                      |
Block Size | 512k          (IOPS) | 1m            (IOPS)
  ------   | ---            ----  | ----           ----
Read       | 474.42 MB/s    (926) | 472.32 MB/s    (461)
Write      | 499.63 MB/s    (975) | 503.77 MB/s    (491)
Total      | 974.05 MB/s   (1.9k) | 976.10 MB/s    (952)

iperf3 Network Speed Tests (IPv4):
---------------------------------
Provider        | Location (Link)           | Send Speed      | Recv Speed
                |                           |                 |
Clouvider       | London, UK (10G)          | 1.19 Gbits/sec  | 2.39 Gbits/sec
Online.net      | Paris, FR (10G)           | 2.35 Gbits/sec  | 2.04 Gbits/sec
WorldStream     | The Netherlands (10G)     | 2.17 Gbits/sec  | 1.29 Gbits/sec
Wifx            | Zurich, CH (10G)          | 1.28 Gbits/sec  | 522 Mbits/sec
Biznet          | Jakarta, Indonesia (1G)   | 19.4 Mbits/sec  | 41.8 Mbits/sec
Clouvider       | NYC, NY, US (10G)         | 9.40 Gbits/sec  | 9.41 Gbits/sec
Velocity Online | Tallahassee, FL, US (10G) | 2.39 Gbits/sec  | 2.94 Gbits/sec
Clouvider       | Los Angeles, CA, US (10G) | 2.40 Gbits/sec  | 2.89 Gbits/sec
Iveloz Telecom  | Sao Paulo, BR (2G)        | 136 Mbits/sec   | 192 Mbits/sec

iperf3 Network Speed Tests (IPv6):
---------------------------------
Provider        | Location (Link)           | Send Speed      | Recv Speed
                |                           |                 |
Clouvider       | London, UK (10G)          | 803 Mbits/sec   | 2.09 Gbits/sec
Online.net      | Paris, FR (10G)           | 2.32 Gbits/sec  | 2.20 Gbits/sec
WorldStream     | The Netherlands (10G)     | 1.95 Gbits/sec  | 1.49 Gbits/sec
Wifx            | Zurich, CH (10G)          | 168 Mbits/sec   | 579 Mbits/sec
Clouvider       | NYC, NY, US (10G)         | 9.28 Gbits/sec  | 9.28 Gbits/sec
Clouvider       | Los Angeles, CA, US (10G) | 2.80 Gbits/sec  | 2.90 Gbits/sec

Geekbench 4 Benchmark Test:
---------------------------------
Test            | Value
                |
Single Core     | 6035
Multi Core      | 24473
Full Test       | https://browser.geekbench.com/v4/cpu/15770150

Geekbench 5 Benchmark Test:
---------------------------------
Test            | Value
                |
Single Core     | 1348
Multi Core      | 5857
Full Test       | https://browser.geekbench.com/v5/cpu/3844555
```

**Comment by cp6** [comment]
That one wont work because its got the geekbench 4 in it.

Try this one:

```
# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #
#              Yet-Another-Bench-Script              #
#                     v2020-12-29                    #
# https://github.com/masonr/yet-another-bench-script #
# ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #

Thu Jan 21 19:29:00 EST 2021

Basic System Information:
---------------------------------
Processor  : AMD Ryzen 7 3700X 8-Core Processor
CPU cores  : 1 @ 3593.246 MHz
AES-NI     : ✔ Enabled
VM-x/AMD-V : ✔ Enabled
RAM        : 991.0 MiB
Swap       : 0.0 KiB
Disk       : 9.8 GiB

fio Disk Speed Tests (Mixed R/W 50/50):
---------------------------------
Block Size | 4k            (IOPS) | 64k           (IOPS)
  ------   | ---            ----  | ----           ----
Read       | 512.20 MB/s (128.0k) | 4.05 GB/s    (63.3k)
Write      | 513.55 MB/s (128.3k) | 4.07 GB/s    (63.6k)
Total      | 2.48 GB/s   (256.4k) | 8.92 GB/s   (127.0k)
           |                      |
Block Size | 512k          (IOPS) | 1m            (IOPS)
  ------   | ---            ----  | ----           ----
Read       | 4.39 GB/s     (8.5k) | 4.22 GB/s     (4.1k)
Write      | 4.62 GB/s     (9.0k) | 4.50 GB/s     (4.4k)
Total      | 9.82 GB/s    (17.6k) | 9.03 GB/s     (8.5k)

iperf3 Network Speed Tests (IPv4):
---------------------------------
Provider        | Location (Link)           | Send Speed      | Recv Speed
                |                           |                 |
Clouvider       | London, UK (10G)          | 2.26 Gbits/sec  | 2.19 Gbits/sec
Online.net      | Paris, FR (10G)           | 2.37 Gbits/sec  | 865 Mbits/sec
WorldStream     | The Netherlands (10G)     | 980 Mbits/sec   | 1.82 Gbits/sec
Biznet          | Jakarta, Indonesia (1G)   | 907 Mbits/sec   | 698 Mbits/sec
Clouvider       | NYC, NY, US (10G)         | 2.79 Gbits/sec  | 2.34 Gbits/sec
Velocity Online | Tallahassee, FL, US (10G) | 2.31 Gbits/sec  | 2.77 Gbits/sec
Clouvider       | Los Angeles, CA, US (10G) | 8.88 Gbits/sec  | 8.91 Gbits/sec
Iveloz Telecom  | Sao Paulo, BR (2G)        | 274.1 Mbits/sec  | 1.00 Gbits/sec

Geekbench 5 Benchmark Test:
---------------------------------
Test            | Value
                |
Single Core     | 1282
Multi Core      | 1142
Full Test       | https://browser.geekbench.com/v5/cpu/6026646
```

**Comment by Mio-sha512** [comment]
I just realised that too when you wrote that message but its not working

**Comment by cp6** [comment]
I just did a re-deploy with the dev branch, fresh db from the `my_idlers.sql` and it worked. Im not sure why it isnt for you, what OS/webserver are you using for it?

**Comment by Mio-sha512** [comment]
Ubuntu 18.04 + Apache2 + PHP 7.4 (default install and config files)
```
Server version: Apache/2.4.29 (Ubuntu)
Server built:   2020-08-12T21:33:25
```
```
PHP 7.4.14 (cli) (built: Jan 13 2021 08:04:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.14, Copyright (c), by Zend Technologies
```

**Comment by Mio-sha512** [comment]
I must be missing a module of somesorts i can't see any other problem

**Comment by cp6** [comment]
Hmmm check permissions. The YABs data gets written to a `yabsFromForm.txt` in the project root and then into `yabs/`

**Comment by Mio-sha512** [comment]
Well now i just fell very dum i changed the perms an it worked thanks for the help sorry for wasting your time

**Comment by cp6** [comment]
@Mio-sha512 Its ok!. Im just glad it worked :)
